### ISSUE TITLE
API: paradigm should be dataframes

### ISSUE THREAD

**Issue by GaelVaroquaux** [nistats/nistats#1]
Looking at the code in experimental_paradigm.py:

- paradigms objects are really data containers (and fairly simple ones)

- the code in the module is for I/O of these to CSV files, and for checking their consistency

- there are 2 types of paradigms, event and block

- paradigms are are defined by a small number of named lists that have the same number of entries:
     - event: cond_id, onset, amplitude 
     - block: cond_id, onset, duration and amplitude

All this makes me think that paradigm objects could be replaced by pandas dataframe with the corresponding entries, and a few functions, in particular something like a '_check_paradigm' for our own internal usage that would take a pandas dataframe and validated it as a block or event paradigm and if it is not valid raise an understandable error. Pandas would provide the reading and writing CSVs.

**Comment by bthirion** [comment]
Solved. closing.
