### ISSUE TITLE
Event related analysis example

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#101]
I think an event related example would be welcome since FIR models are already implemented. Something simple like taking a mask in motor areas and show different activation for button presses? 

This example could lead to a small utility to plot the time series adjusted by other regressors.

Also this example could lead to a small utility to do time series averaging from design to compare with FIR

**Comment by bthirion** [comment]
OK, I am not completely familiar with this type of analysis (what do you _really_ expect from it ?), but if you can put together a compelling example, that would be great.

**Comment by MartinPerez** [comment]
A good complex example would be the PNAS paper Cortical representation fo the constituent structure of sentences: http://www.pnas.org/content/108/6/2522.short

But also is a good sanity check to have on the voxel with peak activity in a cluster, to check that the events specification is correct.

I thought of just using button presses for a sanity check kind of example in a voxel of peak activity. Maybe also in a motor cortex ROI from some standard atlas.

**Comment by bthirion** [comment]
More example is always better, so, yes, I agree in principle.

**Comment by bthirion** [comment]
OK, I think there's nothing to be done concretely on that one. Closing.
