### ISSUE TITLE
fir regressor names do not reflect onsets

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#103]
I realized FIR regressors names drop decimals in onsets. For example 1.5 would become 1 in the name. I think this leads to unexpected naming patterns from the user point of view. Should we modify this?:

```
elif hrf_model == 'fir':
    return [con_name + "_delay_%d" % i for i in fir_delays]
```

**Comment by bthirion** [comment]
Certainly. Bzw I think that the  `fir_delays` parameter is not well described in the doctrings (it is not fully clear that the values  represent time in seconds -- which they should)

**Comment by MartinPerez** [comment]
I will work on this when I get hands on #101
