### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by effigies** [nistats/nistats#135]
Is there a rough timetable for release?

**Comment by bthirion** [comment]
Should have done it already ;-) The plan is to do a first release of the library as-is.
My impediment is to  dedicate some time for that. As I'm travelling this week, this is not ideal.
If I can save time ob Oct 27th, will work on it then.

**Comment by effigies** [comment]
Sounds good. Looking forward to pip install and online docs. :-)

**Comment by MartinPerez** [comment]
Hi I will also dedicate time for the release starting next week.

**Comment by bthirion** [comment]
CLosed by 0.0.1.a release
