### ISSUE TITLE
shorter and more consistent naming

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#141]
like first_level instead of first_level_model

**Comment by kchawla-pi** [comment]
I think `first_level_model` is better. Pretty much all users will use autocomplete so they don't have to type it manually. However, reading `first_level_model` immediately clues a newbie to fMRI what the function might be about, where as `first_level` doesn't.

**Comment by bthirion** [comment]
Non consensus here. Let's revisit that later.
