### ISSUE TITLE
Toward release 0.0.1a

### ISSUE THREAD

**Issue by GaelVaroquaux** [nistats/nistats#142]
* [x] Merge openneuro example
* [x] Merge SPM auditory example
* [x] Bump nibabel requirement to 2.0.2
* [x] Merge better use of nibabel
* [x] Reorder example (with tutorials on top)
* [x] Red banner in docs
* [x] Make nistats/nistats.github.io repo for docs (as with nilearn)
* [x] Bump version number in docs/conf.py, setup.py, tag and push to pypi

**Comment by MartinPerez** [comment]
refactor plotting.py, keep a no matplotlib version test

**Comment by bthirion** [comment]
Done now.
