### ISSUE TITLE
clean webpage simple example upload

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#151]
There is a file that should not be there in simple examples.

**Comment by MartinPerez** [comment]
the old GLM fitting in second level fMRI example file was copied also by accident.

**Comment by bthirion** [comment]
You mean, the plot_101 ?
OK, I'll remove it.

**Comment by MartinPerez** [comment]
no, I mean in general examples the "GLM fitting in second level fMRI", that has to be removed, it is repeated in the second level section

**Comment by bthirion** [comment]
Note sure I get what you mean. I think that keeping 
03_second_level_models/plot_second_level_button_press.py
is very important because it is something that can be reused easily, even without running the whole framework.

**Comment by MartinPerez** [comment]
its not a problem with the repository, but the website. Simply re-uploading the website after merging #153 will fix the issue. If you open the website you will see that the second level example appears in two sections (in general examples and second level models).

**Comment by kchawla-pi** [comment]
@GaelVaroquaux `make install` fails at the push stage, citing I don't have permission to do that.

**Comment by bthirion** [comment]
Should be fine now. B

**Comment by GaelVaroquaux** [comment]
I think that indeed the permissions were not set correctly on this repo, and the admin team did not have the rights. I fixed it.

**Comment by kchawla-pi** [comment]
Fixed with #222
