### ISSUE TITLE
GLM on the cortical surface

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#152]
People would like to run the GLM on the corticalsurface.
THis could be implemented easily by relying on recent nilearn surface projection functions.

**Comment by demianw** [comment]
@bthirion I would be glad to chip in on this one. Seems that the main point is to make a meta pipeline where you sample the surface from the image and then execute GLM (using [nistat's GLM](https://nistats.github.io/modules/generated/nistats.first_level_model.run_glm.html#nistats.first_level_model.run_glm)) ? Am I understanding your idea well?

**Comment by bthirion** [comment]
Yes. I would do that as an example to start with and then see how to factor contributions into modules.

**Comment by bthirion** [comment]
Addressed by #196

**Comment by bthirion** [comment]
Closing, since this has been addressed
