### ISSUE TITLE
scipy not listed as dependency in setup.py

### ISSUE THREAD

**Issue by chrisfilo** [nistats/nistats#154]
```
$ source activate myenv
(myenv)
filo@MSI MINGW64 ~
$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'scipy'
>>> quit()
(myenv)
filo@MSI MINGW64 ~
$ pip install nistats
Collecting nistats
  Using cached nistats-0.0.1a0-py2.py3-none-any.whl
Collecting nibabel>=2.0.2 (from nistats)
  Downloading nibabel-2.2.1.zip (4.2MB)
    100% |████████████████████████████████| 4.2MB 2.8MB/s
Collecting numpy>=1.7.1 (from nibabel>=2.0.2->nistats)
  Using cached numpy-1.13.3-cp36-none-win_amd64.whl
Collecting six>=1.3 (from nibabel>=2.0.2->nistats)
  Using cached six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: nibabel
  Running setup.py bdist_wheel for nibabel ... done
  Stored in directory: C:\Users\filo\AppData\Local\pip\Cache\wheels\9d\a8\5c\5c3f7aeb5b8abf5da0aae7b17eadbac2d652a63bedff0111bd
Successfully built nibabel
Installing collected packages: numpy, six, nibabel, nistats
Successfully installed nibabel-2.2.1 nistats-0.0.1a0 numpy-1.13.3 six-1.11.0
(myenv)
filo@MSI MINGW64 ~
$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from nistats import regression
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\filo\Anaconda3\envs\myenv\lib\site-packages\nistats\__init__.py", line 32, in <module>
    _check_module_dependencies()
  File "C:\Users\filo\Anaconda3\envs\myenv\lib\site-packages\nistats\version.py", line 124, in _check_module_dependencies
    install_info=module_metadata.get('install_info'))
  File "C:\Users\filo\Anaconda3\envs\myenv\lib\site-packages\nistats\version.py", line 74, in _import_module_with_version_check
    module = __import__(module_name)
ModuleNotFoundError: No module named 'scipy'
```

**Comment by chrisfilo** [comment]
Same thing for `sklearn`.

**Comment by chrisfilo** [comment]
And `patsy`

**Comment by bthirion** [comment]
Hm, this should be captures by travis: it means that we are not testing well enough.
Let me try and fix it.

**Comment by bthirion** [comment]
I don't find what's missing. @lesteve Any hint on that ? 
Could it be related to Python 3.6 ?

**Comment by bthirion** [comment]
@chrisfilo Do you hit the same issue with nilearn ?

**Comment by lesteve** [comment]
I think not specifying requirements in setup.py is a long-standing decision that scikit-learn has taken mostly for historical reasons (basically before wheels existed).

For more context, see for example https://github.com/scikit-learn/scikit-learn/issues/4164#issuecomment-71550942.

AFAIK scikit-learn may be open to change this but this is probably a bit of work to convince people, for example:
* https://github.com/scikit-learn/scikit-learn/pull/4371#issuecomment-97015517
* https://github.com/scikit-learn/scikit-learn/issues/9519#issuecomment-321932579

**Comment by chrisfilo** [comment]
This would not explain why `patsy` or `scikit-learn` itself is not installed. It seems that the `requred_at_installation` logic is reversed in https://github.com/nistats/nistats/blob/master/nistats/version.py

**Comment by lesteve** [comment]
The pattern very likely comes from nilearn and I may even have written it at one point. The idea (still for the same reasons in a world without reliable wheels for all platforms) is that:
* we want users to install the dependencies requiring compilation (numpy, etc ...) in a first separate step
* then they can do `pip install nilearn`. If they skip the first step `pip install nilearn` should give a nice error message pointing them to installation instructions (with these two steps).

In other words we don't want packages that require compilation included in our setup.py. This is the case for scikit-learn and patsy I guess since it seems to require numpy.

Having said that, I see that nibabel has numpy in its setup.py, so numpy will be installed anyway when doing `pip install nilearn`. Maybe this is time to revisit all this and include our dependencies in our setup.py to be perfectly honest. cc @GaelVaroquaux @KamalakerDadi.

To make things a bit worse:
* it doesn't seem like `pip install nilearn` give you a nice error if you don't have scipy installed. I am pretty sure it did at some point, but maybe this was with old versions of pip.
* even with `python setup.py install` the nice error message pointing to installation instructions is only shown for Python 2 and not Python 3.

**Comment by KamalakerDadi** [comment]
I am happy to try and issue a PR.

>it doesn't seem like pip install nilearn give you a nice error if you don't have scipy installed.

No. Recently I saw a reported issue in nilearn with Python 3.5. Error message is "no module named 'scipy' or 'sklearn'"

**Comment by bthirion** [comment]
Sure. Please address that in Nilearn, then we'll propagate the fix to nistats.

**Comment by lesteve** [comment]
@KamalakerDadi ping me if you need some help on the nilearn front. There was some related activity in scikit-learn some expert comment on this: https://github.com/scikit-learn/scikit-learn/issues/7867#issuecomment-355204398.

**Comment by KamalakerDadi** [comment]
Sure. Thank you.

**Comment by KamalakerDadi** [comment]
Small update: 
The way the exception is raised is changed from Py 3.3.
Before Py 3.3 ```ImportError``` and from Py 3.3 ```ModuleNotFoundError```.

**Comment by lesteve** [comment]
Ah good point. If I were you I would wait for https://github.com/scikit-learn/scikit-learn/pull/10402 (best PR candidate so far) to be merged and then follow the same pattern in nilearn (and then in nistats).

**Comment by KamalakerDadi** [comment]
If I get it correctly, our code checks the dependencies first and raises an error if they are not already installed. The patch I saw in mentioned PR is adding dependencies to install_requires and installed through setup. If I am right on this. This means that we need major changes to adapt to sklearn pattern. Isn't it ?
I hope I am clear here about asking.

**Comment by lesteve** [comment]
I think you are right although, but let's just wait how it unrolls on the scikit-learn side before discussing in more details.

I would not say it is a major change in terms of approach (basically with wheels putting requirements in setup.py becomes workable) but not in terms of code.

**Comment by KamalakerDadi** [comment]
@chrisfilo Could you please test this patch in PR #163 ? This tells us if we are in the right order of logic at ```required_at_installation``` and displaying error in a user friendly information for Python 3.

Thanks a lot.
