### ISSUE TITLE
Unclear doc for make_design_matrix

### ISSUE THREAD

**Issue by CherkaouiHamza** [nistats/nistats#157]
I found difficult to understand the API of make_design_matrix.

The crucial informations to design properly the matrix are in experimental_paradigm.py... But it takes some time and bugs to understand it, since the documentation of make_design_matrix does not precise this...

Some simple examples may be appreciated.

**Comment by bthirion** [comment]
Indeed, a reminder about #59.
Can you issue  PR ?

**Comment by CherkaouiHamza** [comment]
Alright, I will soon propose a PR.

**Comment by CherkaouiHamza** [comment]
For the example of the DMN extraction with a GLM approach. I will need a new datasets, thus I think I will need to add a new fetcher in "datasets.py". Are you ok with that @bthirion ? 
If yes, can you point out a proper dataset?

**Comment by bthirion** [comment]
Use a dataset from Nilearn, e.g. adhd
You can get inspiration from 
http://nilearn.github.io/auto_examples/03_connectivity/plot_seed_to_voxel_correlation.html#sphx-glr-auto-examples-03-connectivity-plot-seed-to-voxel-correlation-py

**Comment by bthirion** [comment]
Closing this issue. Thx
