### ISSUE TITLE
missing assert in design_matrix.py ?

### ISSUE THREAD

**Issue by josephsmann** [nistats/nistats#159]
line 348: 
```
    if paradigm is not None:
        # create the condition-related regressors
        if isinstance(hrf_model, _basestring):
            hrf_model = hrf_model.lower()
        matrix, names = _convolve_regressors(
            paradigm, hrf_model, frame_times, fir_delays, min_onset)
```
I believe that ```assert( len(paradigm) == len(frame_times)``` would be useful.
Can someone tell me if whether the condition is an appropriate expectation.

thx.

Didn't know if I should make an issue, or a PR..

**Comment by bthirion** [comment]
I don't understand your point: a paradigm has no length, it is a sent of events that occur at some point in time. Ideally, you would like their onset to be in the span of frame_times, but in some cases with variable duration for events, it may not even be always the case.

**Comment by josephsmann** [comment]
I thought it should: in the parameters comments for `make_design_matrix(..)`
it says: 
>    paradigm : DataFrame instance, optional
>        Description of the experimental paradigm.

so, its a DataFrame, and has a length. right?

this is consistent with line 67 in the example: plot_spm_multimodal_faces.py 

hope this helps?

**Comment by bthirion** [comment]
Yes. Let me clarify:
you can have 
* frame_trimes = range(200)
* Say 7 events, with onset 10, 45, 80, 115, 150, 185, 210, duration = 5, and event_type = "flashing checkerboard"
Note that one event has onset 210 > 200, which means that it won't be sampled in the design matrix. this hints at an issues in the experimental design, but does not prevent us from building the design matrix -- that will contain the other events.

len(paradigm) = 7, but ovbiously this number is arbitrary, I could have chosen instead to have 2, 19 or 53 events. This means that there is no simple test that we can do to compare frame_times with the paradigm. 

The only test that would make sense would be to check that 0 < onset < frame_times.max(), but even this is not a strict requirement: we can build a valid design matrix even if this is not fulfilled.

**Comment by josephsmann** [comment]
really appreciate this explanation. all makes sense now.
thank-you.
