### ISSUE TITLE
boto3 is acting as a dependency to install

### ISSUE THREAD

**Issue by KamalakerDadi** [nistats/nistats#160]
boto3 is written instructions as to be installed if needed to download data from openneuro. But, without installing boto3 I could not able to import datasets module.

I think boto3 needs to be imported at function level than module level.

**Comment by bthirion** [comment]
Agreed. @MartinPerez any opinion ?

**Comment by MartinPerez** [comment]
I agree too, this is only necessary to interact with amazon services specific to BIDS datasets.
