### ISSUE TITLE
Importing the reporting module changes appearance of unrelated plots

### ISSUE THREAD

**Issue by effigies** [nistats/nistats#164]
Libraries modifying matplotlib global state can make life difficult for downstream developers. Nistats does this at present:

https://github.com/nistats/nistats/blob/5745e7b6ffadc49b2c2b5c6948f4bb8a61bd7935/nistats/reporting.py#L16

Something I've looked into are [matplotlib style sheets](https://matplotlib.org/users/style_sheets.html) which can be used as context managers. Not quite as low-overhead as setting and forgetting, but less likely to cross package boundaries.

Do you have anybody with time to address this? If not, I can submit a PR.

**Comment by bthirion** [comment]
You're right. PR welcome !
