### ISSUE TITLE
issue with fetch_auditory

### ISSUE THREAD

**Issue by rschmaelzle** [nistats/nistats#168]
Hi,
i am following the link on the website asking for alpha-testing. I repeatedly run into an issue when running fetch_spm_auditory() , which gives: "ImageFileError: Filespec "/home/jovyan/nilearn_data/spm_auditory/sub001/fM00223/fM00223_004.img" does not look right for class <class 'nibabel.nifti1.Nifti1Image'>". The weird thing is that it did work once after I reinstalled nistats from github, and once also worked with !pip install nistats in jupyter. But now, running the same code (https://mybinder.org/v2/gh/nomcomm/cas992/master), i am running into it again. The nistatsversion is 0.0.1a.
Best R

**Comment by bthirion** [comment]
This is a bug (due to nilearn) fixed in #155.
The only thing I can do for you is make another nistats release... 
Since I'm not sure I can do it quickly, is it possible for you to install nistats from Github ?
Sorry for the inconvenience.

**Comment by rschmaelzle** [comment]
thank you. no problem. I ll work around. good to know what the issue is though.
