### ISSUE TITLE
signal_scaling in FirstLevelModel can not be set to False

### ISSUE THREAD

**Issue by Gilles86** [nistats/nistats#171]
The following line

`if signal_scaling in [0, 1, (0, 1)]:`

Will always return True (False is interpreted as an integer here).

This makes it impossible to refrain from scaling the signal when fitting a first level model.

Here is a small fix:
https://github.com/Gilles86/nistats/tree/fix_first_level_signal_scaling

**Comment by bthirion** [comment]
Can you issue a PR for that ?
(If you're not used to that, you might want to take a look to e.g. http://nilearn.github.io/contributing.html)
Best,

B

**Comment by Gilles86** [comment]
Ah, sorry. I now saw that this issue was fixed in the following commit:
https://github.com/nistats/nistats/commit/7ced0d6d2420f9064afc07dcec7a337e28399cb7#diff-14be50d5fb33e7506ec30ac0161104bd

**Comment by bthirion** [comment]
Can we close the issue ?
