### ISSUE TITLE
Memory Error when computing a F contrast 

### ISSUE THREAD

**Issue by chrplr** [nistats/nistats#175]
Hello,

compute_contrast crashes with a `Memory Error` when trying to compute a F contrast (300 lines, 305 cols), 

- the design matrix has shape  (2816, 305)
- this happens whether the noise_model is set to 'ols' or 'ar1'
- the data is not voluminous (the sole nii.gz file is 1.2GB) 
- the PC has 128GB of RAM, so it is most likely not due not enough RAM.

Here is the error:

---
In [2]: nreg = dtx_mat.shape[1]  # number of regressors
   ...: nn=np.eye(nreg)[0:300, :]  # F test on  the first 300 regressors
   ...: z_map=fmri_glm.compute_contrast(nn, stat_type='F', output_type='z_score')
   ...: 
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-2-1e276517d91c> in <module>()
      1 nreg = dtx_mat.shape[1]  # number of regressors
      2 nn=np.eye(nreg)[0:300, :]  # F test on  the first 300 regressors
----> 3 z_map=fmri_glm.compute_contrast(nn, stat_type='F', output_type='z_score')

~/.local/lib/python3.6/site-packages/nistats-0.0.1a0-py3.6.egg/nistats/first_level_model.py in compute_contrast(self, contrast_def, stat_type, output_type)
    549 
    550         contrast = _fixed_effect_contrast(self.labels_, self.results_,
--> 551                                           con_vals, stat_type)
    552 
    553         estimate_ = getattr(contrast, output_type)()

~/.local/lib/python3.6/site-packages/nistats-0.0.1a0-py3.6.egg/nistats/contrasts.py in _fixed_effect_contrast(labels, results, con_vals, contrast_type)
     85             warn('Contrast for session %d is null' % i)
     86             continue
---> 87         contrast_ = compute_contrast(lab, res, con_val, contrast_type)
     88         if contrast is None:
     89             contrast = contrast_

~/.local/lib/python3.6/site-packages/nistats-0.0.1a0-py3.6.egg/nistats/contrasts.py in compute_contrast(labels, regression_result, con_val, contrast_type)
     56 
     57     effect_ = np.zeros((dim, labels.size))
---> 58     var_ = np.zeros((dim, dim, labels.size))
     59     if contrast_type == 't':
     60         for label_ in regression_result:

MemoryError: 
---
==========================================================
Here is the code, runnable at Neurospin

```python
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import nistats
from nistats.first_level_model import FirstLevelModel
from nistats.reporting import plot_design_matrix
from nilearn.plotting import plot_stat_map
from nilearn.plotting import plot_glass_brain

imgs = '/neurospin/unicog/protocols/IRMf/LePetitPrince_Pallier_2018/MRI/english-fmri-data/all.nii.gz'
dtx_mat = pd.read_csv('/neurospin/unicog/protocols/IRMf/LePetitPrince_Pallier_2018/MRI//lpp-results/model-sneza-design-matrices/dmtx_all.csv', delimiter=',')
dtx_mat.shape

fmri_glm = FirstLevelModel(
            t_r = 2.0,
            hrf_model = 'spm',
            # mask='mask_ICV.nii',
            noise_model = 'ols', # ar1
            period_cut = 128.0,
            smoothing_fwhm = 0,
            minimize_memory = True,
            memory='/volatile/nistats-cache',
            #memory = None,
            verbose = 2,
            n_jobs = -1)

fmri_glm = fmri_glm.fit(imgs, design_matrices=dtx_mat)

from nistats.reporting import plot_design_matrix
plot_design_matrix(fmri_glm.design_matrices_[0])
plt.show()

nreg = dtx_mat.shape[1]  # number of regressors
nn=np.eye(nreg)[0:300, :]  # F test on  the first 300 regressors
z_map=fmri_glm.compute_contrast(nn, stat_type='F', output_type='z_score')
```

**Comment by bthirion** [comment]
As you can see, as an intermediate step, the code creates the covariance matrix of the estimates in each voxels. This is OK for standard contrast but blows up with large number of contrasts.
* the correct fix to that is to find an alternative way to handle F contrasts: computing simply the difference of sum of squares of  the residuals for the full and partial model, respectively. This will avoid manipulating all the inverse matrices. It's going to take time to implement and check that.
* A sort-term workaround is simply to run the model on small batches of voxels, using e.g. a parcellation.

**Comment by chrplr** [comment]
I can indeed fit the full and partial models. Will there be an easy way to compute the SS in each voxel then ?

**Comment by chrplr** [comment]
I can indeed fit the full and partial models. Will there be an easy way to compute the SS in each voxel then ?

**Comment by bthirion** [comment]
I think I have the fix for it, on the recent branch I've just created. Let me try and if it's working on your data and if yes I issue a PR.
