### ISSUE TITLE
Return multiple outputs from compute_contrast

### ISSUE THREAD

**Issue by tyarkoni** [nistats/nistats#180]
In the first-level model, [`compute_contrast`](https://github.com/nistats/nistats/blob/master/nistats/first_level_model.py#L487) takes an `output_type` argument to indicate which map should be returned. It looks like this can only be one of several predetermined strings, which means if one wants to get multiple outputs (e.g., `effect_size` and `z`), the method has to be called multiple times. This seems both inefficient (computation doesn't appear to be cached as far as I can tell) and unwieldy. Is there any reason not to return the entire `Contrast` object and let the user pick out what they want from it? If backward compatibility is desirable, maybe `output_type` could take another value `all` or `Contrast`, in which case the actual `Contrast` is returned?

Assuming the latter is agreeable, we can work up a PR for this (looping in @effigies and @adelavega).

**Comment by bthirion** [comment]
H,
We certainly don't want to return an object, because objects are hard to understand. Instead, we want the inputs/outputs to be only NiftiImages or other simple things.
I prefer the 'all' return argument. Does that work for you ?

**Comment by effigies** [comment]
Or are you suggesting return the `Contrast` object on `'all'`, but just rejecting the notion of returning it by default? (My previous comment was interpreting you as never wanting to return a `Contrast`.)

**Comment by tyarkoni** [comment]
I'd be fine with any of the above proposals... `dict` or `namedtuple` would be just fine too. I get the point about wanting to keep the returned values simple by default, but I do think the API should ideally cater to some degree to power users as well. For example, one limitation of *not* making it possible to get a `Contrast` is it prevents access to some of the useful functionality of that object--e.g., calling `stat()` with a `baseline` value other than `0.0`. Which means that if we ever want to efficiently support testing of alternative nulls in fitlins, we would have to duplicate a bunch of your code internally. I think having an `'object'` value for `output_type` would provide the best of both worlds, as it's unlikely that a naive user would choose that option if they don't know what it means.

**Comment by bthirion** [comment]
I'd rather have `all` return a dictionary. The problem with returning objects is code maintenance: people will complain because it's 'broken', or doesn't do what they want to , and you can't even understand what's going on.
2 additional points:
* In my experience, the cost of contrasts computation is fairly small wrt e.g. GLM estimation. Hence I have not worried about optimizing that part. Do you have experience of the converse ?
* I know that testing against a different baseline is indeed a valid usecase, but I never do it myself and never see it done; you suggest it's important for you ?

**Comment by tyarkoni** [comment]
I'm not worried so much about estimation efficiency as about verbosity/clarity of code... it just seemed a bit clunky to have to loop over any desired statistics on the user's end, instead of retrieving everything from nistats and then directly accessing whichever properties one needs. I agree that returning a dictionary via `'all'` would address that.

Re: testing against a non-zero null, no, I can't think of a common use case for that--I was just giving it as one example, off-the-top of my head, for why it might be helpful for users of your API to be able to access nistats objects without having to reimplement contrast computation. I think there are probably other much more common reasons--e.g., wanting to know the `.dof` or `.dim` of the contrast. To my mind the general principle is just that if there's a good reason to maintain state and functionality in a `Contrast` object internally (and I think there is), then it seems like there are probably also going to be good reasons why a user might want to retain access to that object in their own code. But I defer to you on this, of course, and at least for our proximal need, a dictionary is totally fine. Thanks for the quick response!

**Comment by bthirion** [comment]
@GaelVaroquaux any opinion on these matters ?

**Comment by bthirion** [comment]
Do you want to issue a PR ? Note sure I can work on it tomorrow.
Best,
B

**Comment by effigies** [comment]
I can submit a PR tonight or tomorrow morning.

**Comment by bthirion** [comment]
Thx. B

**Comment by effigies** [comment]
Ah, sorry, I dropped the ball on this last week. PR submitted.
