### ISSUE TITLE
Bug: Oversampling during convolution with a high temporal resolution regressor

### ISSUE THREAD

**Issue by adelavega** [nistats/nistats#182]
Given a regressor with high temporal frequency (in this example, speech word onset in a movie), it seems that the re-sampling ("oversampling") produces strange results in `make_design_matrix`.

For example, this is my regressor (this is the output of `check_paradigm`). Onsets are sometimes only a few milliseconds apart, and durations are similarly short. (onset is in seconds, TR=1.5)
![image](https://user-images.githubusercontent.com/2774448/40755548-75a8e9c4-6444-11e8-94b2-10ecf7e5cfbe.png). 

Given the default oversampling of 16, the following regressor is created:

     import nistats.hemodynamic_models as hm
     convolved = hm.compute_regressor(exp_condition, 'glover', frame_times, oversampling=16)[0]
     pd.DataFrame(convolved).plot()

![image](https://user-images.githubusercontent.com/2774448/40755722-31692660-6445-11e8-9e12-59a8b4a27c3b.png)

Raising the oversampling to a higher value (e.g. 50) produces a more sensible result:

![image](https://user-images.githubusercontent.com/2774448/40755717-290e2056-6445-11e8-82d2-50d6e9e0b636.png)

Perhaps, allowing users to access the oversampling parameter from the `make_design_matrix` API would be a good idea, but ideally the default works. This doesn't seem to be a problem with lower resolution events (e.g. every 1-1.5s)

**Comment by bthirion** [comment]
Can you issue a PR ?

**Comment by bthirion** [comment]
Addressed in PR #209

**Comment by bthirion** [comment]
Closing wit merge of #209
