### ISSUE TITLE
Consistent naming of entities

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#184]
make, create, init . They all mean pretty much the same thing in English. It would be poor form for us to name functional entities that switch among these words to describe their behaviour.

One concrete example that prompted this train of thought is from https://nistats.github.io/modules/reference.html
Two functions:

    nistats.design_matrix.make_design_matrix
    nistats.design_matrix.create_second_level_design

When I first saw this, some questions that I thought about:

 - What's the difference between *make* & *create*? 
 - Why are the words different? 
 - Do they mean something specific?

The second function is ``create_second_level_design``. 
 - Where's the ``make_first_level_design``? 
 - Does ``make_design_matrix`` does that?
 - If yes, why is it not called ``make_first_level_design``?
 - Or rather, ``create_first_level_design_matrix``?
 - If *design_matrix* is standard terminaology in fMRI analysism why is it not ``make_first_level_design_matrix`` & ``make_second_level_design_matrix``?

**Comment by bthirion** [comment]
Good point too. I don't see conceptual reasons why we should distinguish between those.
Best.

**Comment by bthirion** [comment]
We should go for `make_first_level_design_matrix` and `make_second_level_design_matrix`.
Thx.

**Comment by kchawla-pi** [comment]
@bthirion once my existing PRs are merged, I will attend to this one. You have anything else I should focus on?

**Comment by kchawla-pi** [comment]
nistats.design_matrix.make_design_matrix -> make_first_level_design_matrix
nistats.design_matrix.create_second_level_design -> make_second_level_design_matrix

nistats.utils.pos_recipr -> We need a better name for this. WHat's he pos for? Says "setting  X>=0 to 0" . How is that positive?
 nistats.utils.multiple_fast_inv ->  nistats.utils.multiple_fast_inverse

To be continued...

**Comment by kchawla-pi** [comment]
Closing for now. Please file issues for future cases.
