### ISSUE TITLE
Avoiding name shortening; explicit is better than implicit or derived.

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#185]
I used to be a big fan of word shortening for naming. `img` instead of `image` and so on. Now, more often than not, I feel they are a bad idea. The benefits disappear, since we & users have autocomplete. 

    nistats.utils.pos_recipr  # Not the best idea.
    nistats.utils.pos_reciprocal  # Better idea.

In the above example, ``pos_reciprocal`` feels so much better to me. 

When I talk about this (such) functions with someone, I automatically say *"pos  reciprocal"*, not *"pos recipr"*. Cutting the word mid-way is a greater cognitive burden for me, and I think, others.

I think it will be better if we consistently use the more informative, slightly longer version; one that agrees with the way we tend to think and speak.

**Comment by bthirion** [comment]
You're right on that !
