### ISSUE TITLE
"3.1.2. GLM fitting in second level fMRI" example does nto run

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#188]
stop inserted

**Comment by kchawla-pi** [comment]
Can you give me some details? Where does the error occur? On my system the example runs fine until the last statement, `plotting.show()`, where it eventually raises an error after printing one window.

**Comment by bthirion** [comment]
Actually it doesn't seem to exist anymore. probably saw that in a corrupted branch. Closing. Sorry for the noise.
