### ISSUE TITLE
Updating CI infrastructure, incl. version bumps

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#204]
The story so far...
With input from @KamalakerDadi 
1. Started transition from CircleCI 1.0 to 2.0. Changed sphinx build to `strict`.
2. During (1), enabled `backreferences_dir` option in nistats docs, which resulted in errors in examples.
3. The error was traced to Pandas dataframes. We decided to update miniconda to use the correct link for miniconda3, like we did in NiLearn. https://github.com/nilearn/nilearn/issues/1672
4. This forced the explicitly specified version of pandas to be installed (0.13) instead of the 0.23 it was defaulting to in the CircleCI 1.0 builds (green), which caused Travis failures.
5. I will now bump up the minimum version for all dependencies, like it was done for NiLearn. GIven the comprehensive role of `pandas`, it will be chosen with some care; probably v0.18, same as NiLearn.
6. Once Travis is green, (1) will proceed as before.

**Comment by bthirion** [comment]
Sounds like a good plan. 
Nistats dependencies should indeed stick to those of Nilearn.
