### ISSUE TITLE
Problems with example 3.2.2. and 3.2.3.

### ISSUE THREAD

**Issue by MichlF** [nistats/nistats#213]
Hi,

I just ran example [3.2.2. ](https://nistats.github.io/auto_examples/01_tutorials/plot_bids_features.html#sphx-glr-auto-examples-01-tutorials-plot-bids-features-py)on a Mac via PyCharm and Anaconda 3.6 python. Download went through without errors but then I got those:

```
/Users/michlf/anaconda3/bin/python /Users/michlf/PycharmProjects/ni-tutorials/BIDSfirstNsecond.py
/Users/michlf/.local/lib/python3.6/site-packages/nistats/first_level_model.py:693: UserWarning: SliceTimingRef not found in file /Users/michlf/nilearn_data/ds000030/ds000030_R1.0.4/uncompressed/sub-10159/func/sub-10159_task-stopsignal_bold.json. It will be assumed that the slice timing reference is 0.0 percent of the repetition time. If it is not the case it will need to be set manually in the generated list of models
  img_specs[0])
/Users/michlf/.local/lib/python3.6/site-packages/nistats/first_level_model.py:465: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  labels, results = mem_glm(Y, design.as_matrix(),
Traceback (most recent call last):
  File "/Users/michlf/.local/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/michlf/nilearn_data/ds000030/ds000030_R1.0.4/uncompressed/derivates/task/sub-10159/stopsignal.feat/stats/zstat12.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michlf/PycharmProjects/ni-tutorials/BIDSfirstNsecond.py", line 65, in <module>
    os.path.join(data_dir, 'derivates', 'task', subject, 'stopsignal.feat', 'stats', 'zstat12.nii.gz'))
  File "/Users/michlf/.local/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/Users/michlf/nilearn_data/ds000030/ds000030_R1.0.4/uncompressed/derivates/task/sub-10159/stopsignal.feat/stats/zstat12.nii.gz'
```

Regarding the last error, the file exists and I should be accessing it as admin/with full rights.

Any idea why it doesn't work? All code is literally copy&paste from the homepage so there should be no typo on my side.

EDIT: I am experiencing another issue with the [3.2.3.](https://nistats.github.io/auto_examples/01_tutorials/plot_spm_auditory.html#sphx-glr-auto-examples-01-tutorials-plot-spm-auditory-py) example (again without any change to the example code).

```
Traceback (most recent call last):
  File "/Users/michlf/.local/lib/python3.6/site-packages/nibabel/filebasedimages.py", line 301, in filespec_to_file_map
    trailing_suffixes=klass._compressed_suffixes)
  File "/Users/michlf/.local/lib/python3.6/site-packages/nibabel/filename_parser.py", line 103, in types_filenames
    % (found_ext, [e for t, e in types_exts]))
nibabel.filename_parser.TypesFilenamesError: File extension ".img" was not in expected list: ['.nii']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/michlf/PycharmProjects/ni-tutorials/UnivariateBlockDesign.py", line 56, in <module>
    subject_data = fetch_spm_auditory()
  File "/Users/michlf/.local/lib/python3.6/site-packages/nistats/datasets.py", line 362, in fetch_spm_auditory
    data = _glob_spm_auditory_data()
  File "/Users/michlf/.local/lib/python3.6/site-packages/nistats/datasets.py", line 346, in _glob_spm_auditory_data
    vol.to_filename(x)
  File "/Users/michlf/.local/lib/python3.6/site-packages/nibabel/filebasedimages.py", line 333, in to_filename
    self.file_map = self.filespec_to_file_map(filename)
  File "/Users/michlf/.local/lib/python3.6/site-packages/nibabel/filebasedimages.py", line 305, in filespec_to_file_map
    filespec, klass))
nibabel.filebasedimages.ImageFileError: Filespec "/Users/michlf/nilearn_data/spm_auditory/sub001/fM00223/fM00223_004.img" does not look right for class <class 'nibabel.nifti1.Nifti1Image'>
```

Maybe related to an update in the nibabel module?

Thanks!

**Comment by bthirion** [comment]
Sorry, what example are you referring to ? I don't see any BIDSfirstNsecond.py in Nistats...
Best,

**Comment by MichlF** [comment]
[Example 3.2.2.](https://nistats.github.io/auto_examples/01_tutorials/plot_bids_features.html#sphx-glr-auto-examples-01-tutorials-plot-bids-features-py)

**Comment by bthirion** [comment]
Thx. This runs well on my laptop and on CircleCI.
Do you mean that you need admin rights to access the file ? If yes, this is an issue, and you should write the files in a place where you can read them without special rights.

**Comment by MichlF** [comment]
I don't know whether I do. This was just a hunch based on the error message. Since the file exists, it seems be related to access rights if the error message is correct. I am just a bit puzzled because the error pops up on two independent systems on which I (checked) have full admin rights and never experienced an access issue before. This made me believe it might be rather related to the file. Or maybe it is related to the python environment?
Are you using Anaconda and/or PyCharm on your laptop?
Does the other example (i.e. 3.2.3) also work on your laptop ?

Thanks for the reply.

**Comment by MichlF** [comment]
This issue can be closed. I fixed the problems.
I do have however a remaining issue that I cannot fix regarding example [3.1.3](https://nistats.github.io/auto_examples/01_tutorials/plot_spm_auditory.html#sphx-glr-auto-examples-01-tutorials-plot-spm-auditory-py) which I falsely labeled 3.2.3 here in this thread.
The problem is identical to what has been earlier reported by claimed to be [fixed](https://github.com/nistats/nistats/issues/168).

`ImageFileError: Filespec "/Users/michlf/nilearn_data/spm_auditory/sub001/fM00223/fM00223_004.img" does not look right for class <class 'nibabel.nifti1.Nifti1Image'>`

I tried converting the image to a nifti, I tried python 2.7. and 3.6. and different OS (Mac/Windows)

**Comment by kchawla-pi** [comment]
Thanks for the follow up. We would appreciate it if you could details how you fixed the problem?

The fix that has been landed are in the master branch of nistats, which will be released to public with the next version of nistats. Are you experiencing the error with the master branch or the one installed using pip/conda?

**Comment by MichlF** [comment]
The fixes where entirely user-sided. I did a full reinstall of my python setup and pycharm only to discover that I must have accidentally added a letter to the path description. So it was indeed not existing.

I have installed the version via conda. So are you saying the issue with 3.1.3 reported earlier and possibly linked to my issue has been fixed but will be published with the next version of nistats? Is there any ETA on the release?

**Comment by kchawla-pi** [comment]
Hey @MichlF I meant to confirm a ballpark time and inform you and  well, I didn't.
We have just pushed the beta release out this morning.
Whenever you decide to upgrade, do let us know if there's anything that should be improved.

**Comment by MichlF** [comment]
Took a while until I could check it but [the univariate example (formerly 3.1.3. now 2.1.2.)](https://nistats.github.io/auto_examples/01_tutorials/plot_single_subject_single_run.html#sphx-glr-auto-examples-01-tutorials-plot-single-subject-single-run-py) works for me now.
There is quite a bunch of deprecation warnings though (using python 3).

**Comment by kchawla-pi** [comment]
Hi @MichlF Thanks for letting us know. If you post a log or the output of the warnings, we will be able to review them and see what we can do.

**Comment by MichlF** [comment]
```
/Users/michlf/anaconda3/envs/fMRI_NRosT/lib/python3.6/site-packages/scipy/ndimage/measurements.py:272: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  return _nd_image.find_objects(input, max_label)

/Users/michlf/.local/lib/python3.6/site-packages/nilearn/_utils/cache_mixin.py:221: DeprecationWarning: The 'cachedir' attribute has been deprecated in version 0.12 and will be removed in version 0.14.
Use os.path.join(memory.location, 'joblib') attribute instead.
  if (memory.cachedir is None and memory_level is not None

/Users/michlf/anaconda3/envs/fMRI_NRosT/lib/python3.6/site-packages/nistats/hemodynamic_models.py:268: DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
  frame_times.max() * (1 + 1. / (n - 1)), n_hr)

/Users/michlf/anaconda3/envs/fMRI_NRosT/lib/python3.6/site-packages/nistats/hemodynamic_models.py:55: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  time_stamps = np.linspace(0, time_length, float(time_length) / dt)

/Users/michlf/anaconda3/envs/fMRI_NRosT/lib/python3.6/site-packages/scipy/linalg/basic.py:1321: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  x, resids, rank, s = lstsq(a, b, cond=cond, check_finite=False)

/Users/michlf/.local/lib/python3.6/site-packages/nilearn/plotting/find_cuts.py:285: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  data[slices] *= 1.e-3

/Users/michlf/anaconda3/envs/fMRI_NRosT/lib/python3.6/site-packages/numpy/matrixlib/defmatrix.py:68: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
  return matrix(data, dtype=dtype, copy=False)

/Users/michlf/.local/lib/python3.6/site-packages/nilearn/_utils/cache_mixin.py:92: DeprecationWarning: The 'cachedir' attribute has been deprecated in version 0.12 and will be removed in version 0.14.
Use os.path.join(memory.location, 'joblib') attribute instead.
  cachedir = memory.cachedir
```

**Comment by kchawla-pi** [comment]
Thanks a lot!
> Some of them are not really from nistats 

That's fine, we will see what we can do to ameliorate this problem from our side. Don't hold back or filter it.

**Comment by bthirion** [comment]
The ones relevant to Nistats are those in `hemodynamic_model`

**Comment by kchawla-pi** [comment]
Closing this one
