### ISSUE TITLE
Documentation of FirstLevelModel is wrong

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#226]
It say that "canonical" and "canonical with derivative"  are possible values for `hrf model`. This is wrong. Should be one of ['spm', 'spm + derivative', 'spm + derivative + dispersion', 'fir', 'glover', 'glover + derivative', 'glover + derivative + dispersion', None]

**Comment by MichlF** [comment]
Also, the link to the nilearn github page under the fit method for parameter run_imgs is dead.

**Comment by bthirion** [comment]
Solved for the moment. Closing
