### ISSUE TITLE
Removing unnecessary wrapper functions

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#229]
@bthirion 
Case in point,
In `nistats.experimental_paradigms.py`, the function `paradigm_from_csv()`. This is the function definition:
```
def paradigm_from_csv(csv_file):
    return pandas.read_csv(csv_file)
```
This is not simplifying anything, as the functions docstring claims. All it is doing is adding another layer of unneeded abstraction, hiding the underlying process and making it more obtuse about what's going on.

If the user wants to import such files with different parameters, such as skip_rows etc, they will resort directly to pandas function anyway.

There are no users who would use `Nilearn` and `Nistats` or any data science and not be well versed in using `pandas` to read `csv` and `tsv` files. 

All the Nilearn examples depend on using pandas to directly load data, so does sckit-learn. If the user has to add `import pandas` at the top of their file, I don't see why that is a problem, they will be importing five different libraries for even the simplest work.

All the documentation and docstring in nistats and nilearn indicate where a pandas dataframe is the expected input.

It would make sense to have a wrapper function if it simplifies the parameters being passed, or clubs a bunch of processes into one higher-order function. This does neither.

We should find such wrappers and eliminate them.

**Comment by bthirion** [comment]
Indeed ! Thx. Please go ahead.
