### ISSUE TITLE
Python 2 & 3 and the future of Nistats

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#233]
Python2 is going to be deprecated from Nilearn v0.5 onwards and phased out in the next two versions of Nilearn. That will be about the time that Nistats will be ready for production release and combining with NIlearn.
We should skip on supporting Python2 for Nistats from the very beginning. By the time we release it, Nilearn will no longer support Python2 or be a month or two away from dropping support for it.
It will simplify development and we will not have to do extra work to phase it out down the line.
Python3 has cleaner programming idioms that we can utilize right away, so the code will be cleaner for long-term maintenance.
Nistats is currently in Alpha stage. This is the perfect time to do this.
I will develop my current code accordingly.

**Comment by bthirion** [comment]
Well, simply remember that many users (e.g. on the default neurospin setup) are on python 2.7.
I think we should send derpecation messages, but still make sure that we support Python2.
We'll drop it definitely with Nilearn 0.7.0

**Comment by kchawla-pi** [comment]
When do we expect Nilearn 0.7.0 to be released? The usual release cadence seems to be 3-4 months. 
Do we help transition Neurospin users to Python3?

**Comment by bthirion** [comment]
I'd say one year.
Sure, we should help Neurospin users to transition.
