### ISSUE TITLE
datasets.fetch_localizer_first_level() returns Connection Refused

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#237]
```
from nistats.datasets import fetch_localizer_first_level

fetch_localizer_first_level(data_dir='/home/kshitij/Desktop')
```
gives

```
URLError: <urlopen error ftp error: [Errno 111] Connection refused>
```
from `master` branch.

**Comment by bthirion** [comment]
Well, the site gets wrong from times to times. We should copy the data somewhere else.

**Comment by kchawla-pi** [comment]
It worked for Kamalaker, not for me and Juan

**Comment by kchawla-pi** [comment]
The problem seems to be when using eduroam, the firewall seems to be denying the connection. When I use my hotspot and at my home it works fine.
This is a problem for the tutorial. @bthirion

**Comment by GaelVaroquaux** [comment]
> Closed #237.

Why did you close?

**Comment by kchawla-pi** [comment]
Seemed like a FTP server problem not a nistats one.

On Oct 8, 2018 20:08, "Gael Varoquaux" <notifications@github.com> wrote:

> Closed #237.

Why did you close?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/nistats/nistats/issues/237#issuecomment-427928546>, or mute
the thread

**Comment by GaelVaroquaux** [comment]
> Seemed like a FTP server problem not a nistats one.

OK. Well, let's see if it comes back to life, and if not, let's use OSF.

**Comment by kchawla-pi** [comment]
The server os working fine, it works if I use my mobile hotspot. It's not working on eduroam, because connection refused.
