### ISSUE TITLE
Using a parametic regressor instead of an categorical for first level models

### ISSUE THREAD

**Issue by bgagl** [nistats/nistats#243]
Hi there, 

I really like nistats and I am currently successful in running first/second level model with categorical predictors (i.e. Cond1 vs. Cond2). But now I am interested in using a numeric predictor value (i.e. stim 1: 1, Stimulus 2: 1, Stimulus 3: 0, Stimulus 4: 2, Stimulus 5: NaN, ....) that changes from stimulus to stimulus and includes NaN and decimal places meaning it's a float. 

When I start to fit the model using this float parameter the following error occures: 

`ValueError: Design matrix columns do not have unique names`

This is the model I am working with: 

```
FirstLevelModel(drift_model='cosine', drift_order=1, fir_delays=[0],
        hrf_model='glover', mask=None, memory=Memory(cachedir=None),
        memory_level=1, min_onset=-24, minimize_memory=True, n_jobs=1,
        noise_model='ar1', period_cut=128, signal_scaling=True,
        slice_time_ref=0.0, smoothing_fwhm=None, standardize=False,
        subject_label='ADA07', t_r=2.25, target_affine=None,
        target_shape=None, verbose=0)
```
which results from the `first_level_models_from_bids` function.

I am not sure if this is a bug or if I am getting something wrong here. Would be great if you could come back to me.

Best wishes,
Benjamin

**Comment by bthirion** [comment]
When you specify the `paradigm` structure, you can add a `modulation` column:
```paradigm = df({'onset' : onset_values, 'trial_type': array_of_string, 'duration': duration_values, 
                         'modulation': modulation_values})```
where `modulation_values = np.array([1, 2, 0, 2, ...])` in your examples

Note however that NaN cannot be handled, as a finite numerical value is needed. You may want to impute missing values e.g. by 0 or by the mean of others etc.

Soes this answer your concern ?

**Comment by bgagl** [comment]
Thanks for that reply, this works but it does not do what I want. Sorry for the misunderstanding, I should have been clearer before. 

The result of the solution you proposed is multiple columns with each representing one numeric value. What I wanted is a single column in the design matrix that includes all these numeric values and then use a regression to correlate this numeric parameter with the brain data. In the end, it is the plan to realize such a regression approach with multiple parameters varying from stimulus to stimulus without any repetition of a numeral. I might have used a wrong approach in the first place.

**Comment by bthirion** [comment]
Sure, but the columns in the `design_matrix` are indexed by the `trial_type` information: so if you specify the same type for all trials:
```
trial_type = np.array(['condition', 'condition',...., 'condition'])
```
The you will have a unique 'condition' column in the design matrix (notwithstanding potential derivative regressors). The trial-specific amplitude will reflect the modulation you provided, which is what you want if I understood correctly.
best,

**Comment by bgagl** [comment]
Thanks, this looks good now!

**Comment by bgagl** [comment]
One more quick question is there a nicer way to remove NaN trails other than removing rows from the design matrix.
