### ISSUE TITLE
plot_second_level_button_press example referred in doc_index.rst

### ISSUE THREAD

**Issue by KamalakerDadi** [nistats/nistats#248]
It seems like this is removed from 03_second_level_models. Needs to be renamed to appropriate example.

For example, you can see here where it is referred

![issue_nistats](https://user-images.githubusercontent.com/11410385/46526266-14856d80-c88e-11e8-8059-201360422f8a.png)

**Comment by KamalakerDadi** [comment]
I don't know which example to replace. That's why I could not do PR.

**Comment by bthirion** [comment]
Could you use e.g. 
03_second_level_models/plot_thresholding.py
Thx !
