### ISSUE TITLE
'botocore' is necessary to use 'datasets' modules

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#254]
It should ot be the case. Botocore should be required only for the functions that need it (very few actually).
The dependece on botocore should be indicated on a by-script/module basis.

**Comment by kchawla-pi** [comment]
Its actually boto3, botocore is installed as part of it. Openneuro uses it for downloads I believe.
> The dependece on botocore should be indicated on a by-script/module basis.

That would be pretty ugly handling. Create an env for nistats based on the documentation and then run into the import error when trying to run the dependent examples? Ugly. Users not used to package management may not immediately think to check pip or conda list for package lists. 
We are installing 20-30 packages for this, one more isn't gonna be a big deal.
