### ISSUE TITLE
Mutable default paramter in first_level_model_from_bids

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#284]
In `nistats.first_level_model.first_level_model_from_bids`, here is the function signature:

`first_level_models_from_bids( task_label, space_label, img_filters=[],...`

Why is a mutable data structure (`[]`) the default arg for `img_filter`? This is generally the cause of hard to diagnose bugs in Python. Any particular reason it has been written this way?

**Comment by bthirion** [comment]
No good reason I believe. We should use `img_filters=None`
