### ISSUE TITLE
first_level_models_from_bids cannot handle multiple tasks in one session

### ISSUE THREAD

**Issue by MichlF** [nistats/nistats#285]
My experiment has two different tasks in one session. Eight runs are labelled task-A for BOLD and events file, while one run is labelled task-B for BOLD and events file. fmri-prep had no issues with this construction. 
However, first_level_models_from_bids does not work because:

`ValueError: 9 events.tsv files found for 8 bold files. Same number of event files as the number of runs is expected`

This is in spite of the task_label being 'A'.

Maybe there should be an extra command/method to separate between different tasks?

**Comment by bthirion** [comment]
Yes, these functions are quite fragile. Do you have the possibility to investigate the error and propose fixes. Part of the solution is probably simply to rely on pybids. But I cannot work on that ATM.

**Comment by MichlF** [comment]
I think I made a mistake. At least I could fix it for me. Sorry about that. I close this (can also be deleted).
