### ISSUE TITLE
Example 3.1.10 needs fixing

### ISSUE THREAD

**Issue by MichlF** [nistats/nistats#286]
Example [3.1.10.](https://15-35545854-gh.circle-artifacts.com/0/home/ubuntu/nistats/doc/_build/html/auto_examples/plot_localizer_analysis.html#sphx-glr-auto-examples-plot-localizer-analysis-py)

```
data = datasets.fetch_localizer_first_level()
paradigm_file = data.paradigm
paradigm = pd.read_csv(paradigm_file, sep=' ', header=None, index_col=None)
```

fetch_localizer_first_level() will not create "paradigm" for this dataset. Also, even after retrieving the correct events path, pd.read_csv() will not properly read in the events file (on a Mac at least) since the tab separation is used.
This should fix it:

```
paradigm_file = data.events
paradigm = pd.read_csv(paradigm_file, sep='\t', header=0, index_col=None)
```

Also, using header=0, automatically reads in the first line as header so `paradigm.columns = ['trial_type', 'onset', 'duration']` can be removed.

**Comment by kchawla-pi** [comment]
Hi @MichlF , This is not the documentation from the official website.

**Comment by MichlF** [comment]
Oh ... my bad. This page looks very similar in terms of layout.
