### ISSUE TITLE
Change frequency cutoff to use Hz instead of second

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#292]
NiLearn frequency cutoff is in Hz.
Ni Stats uses inv frequency/TimePeriod in seconds. 
Make it Hz.

@bthirion Anna-Louisa @alpinho is interested in working on this. Any info helpful to flesh this issue out shold be added here.

**Comment by bthirion** [comment]
The default should be 0.01 Hz, as we do for resting-state (see in Nilearn).
I'm happy to help if you have specific questions.
Thx !

**Comment by alpinho** [comment]
Where is this value stated in Nilearn?

**Comment by bthirion** [comment]
https://github.com/nilearn/nilearn/blob/77dbcfee8fcf93929ad21c51bf607d798c40dd23/nilearn/input_data/nifti_masker.py#L101

**Comment by alpinho** [comment]
My question was related to the value that is assigned to the cutoff frequency. You say that is set by default to 0.01Hz but I cannot find where that is declared.

**Comment by bthirion** [comment]
Right, I can see it in the examples, yet not in the library itself. I still think that this is a good default.
