### ISSUE TITLE
Discrepancy in terms used between Nistats & Nilearn.

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#293]
NiftiMasker defined in FirstLevelModel might be different between NiStats & NiLearn.
Terms to check:
t_r
hi_frequency_cutoff
lo_frequency_cutoff

@bthirion Anna-Louisa @alpinho might be interested in working on this as well. Any helpful info to flesh out this issue should be added here.

**Comment by bthirion** [comment]
@alpinho do you consider  working on it ?

**Comment by alpinho** [comment]
Yes! I will work on it next week.

**Comment by kchawla-pi** [comment]
@bthirion  It occurred to me that it is not straightforward to maintain backward & forward compatibility with this change, based on the changes @alpinho has made so far in her PR #322 . 
Making changes to preserve backward compatibility will not be clean. And once the deprecation period is past, changing it to look clean for future will not be clean.
I may be able to engineer around this using decorators, but I don't think the benefit is worth the cost.

I am thinking that we either forego backward compatibility, or that we make this change in `nilearn.stats` instead and leave this unchanged here

**Comment by bthirion** [comment]
Yes, for Nistats we do not ensure backward compatibility atm.
Please don't add decorators ;-)
B

**Comment by kchawla-pi** [comment]
Cool I will ask Ann-Luisa to just make the changes, that should simplify everything.
