### ISSUE TITLE
Is bundling numpydoc and sphinx_gallery necessary?

### ISSUE THREAD

**Issue by sanjayankur31** [nistats/nistats#300]
Hello,

While packaging nistats for Fedora, this came up in [the review](https://bugzilla.redhat.com/show_bug.cgi?id=1657410). Is bundling numpydoc and sphinx_gallery in the souce necessary---would it not be possible to install them via pip like the other requires/build_requires?

Cheers!

**Comment by kchawla-pi** [comment]
Hi @sanjayankur31 , sphinxgallery is not included in the pip install of nistats. Additionally, its a minor package. Will there be a strong benefit to Fedora if it is removed?

**Comment by sanjayankur31** [comment]
Hi @kchawla-pi. Thanks for your reply. No, not really. I can remove it from the source before building the rpm for Fedora. We notify upstreams for the usual reasons: bundling may result in older versions of library being used and so on. If it makes it more convenient for you (upstream) to generate docs etc., please let it be. 

I've seen some other upstreams use a "requirements-dev.txt" file that lists the "extra" deps that are not to be included in "install_requires"---if that appeals to you as a better method than bundling these requirements?

**Comment by kchawla-pi** [comment]
Thanks for your well considered and helpful response!
I am glad this is not a deal breaker. 
We are gonna let it be for now.
Thanks for packaging Nistats with Fedora!

**Comment by sanjayankur31** [comment]
+1. I'll close this ticket. Thanks for the feedback :)
