### ISSUE TITLE
Anova f test contrast generator

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#31]
I implemented the M-way level Anova F contrast generator as implemented in spm:
http://lsr-web-02.mrc-cbu.cam.ac.uk/personal/rik.henson/personal/PennyHenson_SPM_06b.pdf
Were conditions reflect the factors ordered.

Would this be relevant to nistats?

**Comment by bthirion** [comment]
I think that this is an interesting contribution, that requires two preliminary steps:
* Identify the intended use case, which will constrain the API choice (which models are needed, function naming, choice of parameters, return values, integration with existing functions, which parameters are actually needed). A possibility is to develop a motivating example
* Identify  code for the low level statistical models: ANOVA are pretty standard models, so it would be good to rely as systematically as possible on existing code bases (scipy.stats, pandas etc.)

**Comment by bthirion** [comment]
Seems to be stalled. Closing.
