### ISSUE TITLE
'mask_img' instead of 'mask' in FirstLevelModel and SecondLevelModel specification

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#315]
Nistats is currently not following the Nilearn convention of calling the provided mask 'mask_img'

**Comment by bthirion** [comment]
@kchawla-pi  are you doing this ?

**Comment by kchawla-pi** [comment]
Ok. WIll do tomorrow.

**Comment by bthirion** [comment]
Done in #321 
Closing.
