### ISSUE TITLE
incorrect documentation for period_cut

### ISSUE THREAD

**Issue by poldrack** [nistats/nistats#318]
The documentation for nistats.first_level_model.FirstLevelModel say that period_cut is for a low-pass filter:

```
period_cut : float, optional

    This parameter specifies the cut period of the low-pass filter in seconds for the design matrices.

``` 

when i fact it's for a high-pass filter.  it should also make clear that this is only for the cosine option.

**Comment by bthirion** [comment]
Indeed, thx.
