### ISSUE TITLE
Error when importing nilearn datatset functions

### ISSUE THREAD

**Issue by mrahim** [nistats/nistats#33]
In `dataset.py` the functions :  `_get_dataset_dir, _fetch_files, _fetch_file, _uncompress_file`
have been moved to `nilearn.dataset.utils`.

**Comment by lesteve** [comment]
I think @bthirion was saying that nistats is supposed to work with the latest released nilearn version ...

**Comment by bthirion** [comment]
Yes I'm waiting for the next Nilearn release to update this.
(hence I switch between the two Nilearn versions when needed...)

**Comment by bthirion** [comment]
Solved, closing.
