### ISSUE TITLE
Move HRF utilities into their own package?

### ISSUE THREAD

**Issue by tyarkoni** [nistats/nistats#356]
The HRF module is very useful, so we've bundled it into pybids (I didn't want to make nistats a dependency just for convolution) I imagine it would be beneficial to other people to have a small utility library that does just HRF convolution. @bthirion how would you feel about moving this into its own package? It would make it easier to maintain and ensure that we stay in sync.

**Comment by bthirion** [comment]
To me the answer is no, for two reasons:
* avoid multiplication of packages to maintain (this eventuelly adds work). We had this discussion a couple of years ago about Nilearn, as some people wanted to extract viz utilities from it. I'm glad we did not do it. And not that in the mid term, we plan to merge nistats into nilearn.
* Nistats is a light dependence. What is the issue with depending on it ?
Best,
B

**Comment by tyarkoni** [comment]
That's reasonable. Re: the dependency, nistats itself is light, but it depends on nilearn and sklearn, which are not so light (at least the latter).
