### ISSUE TITLE
circle ci broken by latest matplotlib release

### ISSUE THREAD

**Issue by jeromedockes** [nistats/nistats#358]
the example `plot_localizer_surface_analysis` fails with matplotlib 3.1

since the latest matplotlib release, setting the aspect of an Axes3d results in
a error, which caused an error in nilearn's `plot_surf_stat_map`. The problem
has been fixed in nilearn:

https://github.com/nilearn/nilearn/pull/2070

but the fix has not been released yet.

maybe the simplest strategy is to pin the circle ci matplotlib to an older
version until the next nilearn release.

**Comment by bthirion** [comment]
@kchawla-pi do you want to take care  of that ?

**Comment by kchawla-pi** [comment]
Sure. We already fixed this in Nilearn, it is not a difficult thing.

**Comment by kchawla-pi** [comment]
Since the code that has been rendered incompatible is in Nilearn (fixed in master, not release), I have pinned MPL==3.0.3 in CircleCI Config.
