### ISSUE TITLE
TravisCI failing due to Conda not supporting older versions

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#363]
Travis CI seems to be failing as conda indicates it no longer supports installation of odler versions of SciKit-Learn, SciPy etc in its default channels.

This needs to be fixed by either switching channels or using pip for these packages.

**Comment by bthirion** [comment]
Maybe simply time to switch ?
Best,
B

**Comment by kchawla-pi** [comment]
We can't switch away from Travis unless we do the same with Nilearn, which is not the plan.

**Comment by kchawla-pi** [comment]
We are switching in Nilearn. This repo won't be maintained so I am not making he changes here.
