### ISSUE TITLE
Fix docstring in FirstLevelModel to correct where results are stored

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#370]
As stated by @jeromedockes, in issue #369

this line in the docstring

https://github.com/nistats/nistats/blob/9fa2e0e7cd8a0deed5f57d9645d080b64e671de2/nistats/first_level_model.py#L117

should be fixed to state that by defaults results are stored as `SimpleRegressionResults`, not `RegressionResults`

_Originally posted by @jeromedockes in https://github.com/nistats/nistats/issues/369#issuecomment-512987725_

**Comment by kchawla-pi** [comment]
The original usse-filer has not indicated an interest in fixing this, so I will do it. @jeromedockes

**Comment by bthirion** [comment]
Thx @kchawla-pi

**Comment by kchawla-pi** [comment]
Fixed in #371
