### ISSUE TITLE
CircleCI Failing

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#372]
CIrcleCI is failing on the master branch during package installation step with the error 
`ReadError('file could not be opened successfully')`
https://circleci.com/gh/nistats/nistats/621

This usually means a corrupt/partial download, corrupt cache, or incorrect file association. The latter is highly improbable here, & `master` branch does not use a cache, so my initial thoughts are that the download is either corrupt or incomplete.

This may very well be a matter of waiting a bit & retrying. I'll try a rerun first & then reassess.

**Comment by kchawla-pi** [comment]
The bug is still present. I have some ideas & will work on this.

**Comment by kchawla-pi** [comment]
I am fairly certain this is a conda problem and I have an idea for fixing it.

**Comment by bthirion** [comment]
Congratulations !
