### ISSUE TITLE
Fails to work on data processed in newest version of fMRIPrep

### ISSUE THREAD

**Issue by adamkimbler** [nistats/nistats#377]
For the Bug Report, 
Include this information:
-------------------------
What version of Nistats are you using? 0.0.1b
What were you trying to do? Run first level model on fMRIPrep processed data
What did you expect will happen? it would work
What actually happened? I traced this back to how `first_level_models_from_bids` searches images, it's looking for a file that fits the string `<dataset_path>/<derivatives_folder>/<subject_folder>/func/<subject_label>*_preproc.<file_extension>`  fMRIPrep has switched to using `preproc_bold` in the newest version and is unable to find the new files. As such, the current expression string can't find newly processed files.

**Comment by kchawla-pi** [comment]
Thanks @adamkimbler !
I believe this is being addressed in PRs #373 and #341

Hopefully, we shall be able to merge these soon, so you can atleast use the master while we prepare a new release.

**Comment by gifuni** [comment]
A related issue which I did not see mentioned: The current BIDS standards allow the events.tsv file to be in the main directory (task-<task-label>_events.tsv). In this case, the `first_level_models_from_bids` should also check there for an event.tsv file. 

Plus, the reading function should respect the BIDS inheritance rule: "The values from the top level are inherited by all lower levels unless they are overridden by a file at the lower level". 

Hope this will help improve BIDS compatibility :)

**Comment by kchawla-pi** [comment]
Thanks @gifuni
