### ISSUE TITLE
Color bars for contrast plots

### ISSUE THREAD

**Issue by alpinho** [nistats/nistats#379]
In the GLM report, a gray colorbar should be added to the contrast plots as different beta-estimates may accept different constants in the linear combinations.

**Comment by bthirion** [comment]
Thw for the suggestion.
This should be done in the contrast_plot function, not in the reporting utilities.

**Comment by kchawla-pi** [comment]
The contrast_plot function already supports colorbars. We need to enable that option in GLM Reporter.
