### ISSUE TITLE
fail fetch nipy data

### ISSUE THREAD

**Issue by agramfort** [nistats/nistats#38]
Data absent, downloading...
Extracting data from /Users/alex/nilearn_data/nipy-data-0.2.tar.gz...
Error uncompressing file: CRC check failed 0x23fd1d03 != 0x5f3d7a64L
Archive corrupted, trying to download it again.

**Comment by bthirion** [comment]
I never had that one on Travis nor on my box. Can this be a mac-related 
thing ? Have you already seen this kind of issue previously ?
Best,

B

**Comment by agramfort** [comment]
I had an unfinished downloaded file. works now. Sorry for the noise
