### ISSUE TITLE
Small error in Tutorial 2.1.3

### ISSUE THREAD

**Issue by gifuni** [nistats/nistats#380]
Hi Nistats devs,
I spotted a tiny mistake in the tutorial 2.1.3 Studying first-level-model details in a trials-and-error fashion.

In the code of 2.1.3.4. Changing the hemodynamic response model:
...
contrast_val = np.eye(design_matrix.shape[1])[1:2:21]
z_map = first_level_model.compute_contrast(
    contrast_val, output_type='z_score')
plotting.plot_stat_map(
    z_map, display_mode='z', threshold=3.0, title='effect of time derivatives')
plt.show()
...

To select all derivative regressors, as explained the indexing should read [1:21:2]. Thus, the first line would be:
...
contrast_val = np.eye(design_matrix.shape[1])[1:21:2]
...

**Comment by bthirion** [comment]
Thx for reporting !
Can you issue a PR to address these issues ?
