### ISSUE TITLE
String value not accepted for the 'contrasts' parameter in make_glm_report for second level reports

### ISSUE THREAD

**Issue by swaythe** [nistats/nistats#405]
I was trying to generate reports using make_glm_report() with nistats 0.0.1b for a second level analysis (one sample t-test). The docstring says that the contrasts parameter can take string values, but when I pass it one, I get a KeyError. 
E.g. if contrasts = 'xyz', I get
KeyError: 'xyz'
and also
UndefinedVariableError: name 'xyz' is not defined

The 'contrasts' parameter has no special meaning in this case, so it seems like I should be able to provide any string. I can make the function work if I set contrasts = [1].

**Comment by kchawla-pi** [comment]
@swaythe If you are working with Private data or scripts, you should check tih @bthirion what you can share before posting it here.

**Comment by swaythe** [comment]
Sorry, that was a premature filing. It's not an issue - I was not providing the correct string to 'contrasts'.

**Comment by kchawla-pi** [comment]
If you were not providing the column names from the design matrix, then this might be an opportunity for improving the documentation and the error message in GLM Reporter.
