### ISSUE TITLE
0.0.1c

### ISSUE THREAD

**Issue by effigies** [nistats/nistats#417]
Hi @kchawla-pi, @bthirion. Some new features have gone in recently that it would be nice to be able to use in FitLins. Is there any chance of a 0.0.1c release before the nilearn merge?

**Comment by kchawla-pi** [comment]
Hey! Yes! We will do a final release before we freeze this repo.

**Comment by kchawla-pi** [comment]
@effigies @sanjayankur31 Nistats 0.0.1b3 is now on PyPI

**Comment by effigies** [comment]
Thanks @kchawla-pi!
