### ISSUE TITLE
small typos and language things in some tutorials

### ISSUE THREAD

**Issue by PeerHerholz** [nistats/nistats#432]
Ahoi hoi everyone,

while redoing some of the tutorials I noticed a few small typos and language things and wondered
if it's worth opening a PR or wait till the [Nilearn](http://nilearn.github.io) merge happened as the tutorials will be changed/adapted/updated within this process anyway?

Best regards, Peer

**Comment by bthirion** [comment]
For typose you can open a PR. The sooner the better.
Thx.

**Comment by PeerHerholz** [comment]
I completely forgot to point to the PR. It was already merged, but here it is (was): #436.
Hence, I'll close this issue.
