### ISSUE TITLE
Preparing Nistats for retirement

### ISSUE THREAD

**Issue by kchawla-pi** [nistats/nistats#445]
In preparation for freezing the Nistats repo with one last release, here are my ideas and question:

 - It will be released as 0.0.1rc .
 - The minimum required Nilearn version is 0.4. However I believe we should bump it up, to a minimum 0.5.2, the last release with Python2 support. 0.4 is way too low.
 - I will set a new `max_version` to `0.6.3` , so people with Nilearn 0.7.0 and above cannot install Nistats.

**Comment by bthirion** [comment]
Yes, makes sense.
