### ISSUE TITLE
Documentation accompanying examples

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#45]
Would it be useful for me to compile a small manual based on the examples. It could be the base for some web user documentation?

**Comment by bthirion** [comment]
Yes, for the moment I would simply add a one or two.rst files that describes how to process data with Nistats, relying mostly on the existing examples. 
The idea is to keep it small and simple. 

B

**Comment by MartinPerez** [comment]
ok I will work on that

**Comment by lesteve** [comment]
Generating a website with a gallery of examples is just a matter of using sphinx-gallery. Look at how the doc is set-up for nilearn and ask if you get stuck.

**Comment by MartinPerez** [comment]
I will do that, thanks!
