### ISSUE TITLE
The masker in GLM should be a MultiNiftiMasker

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#48]
in order to support multiple session effectively.

**Comment by MartinPerez** [comment]
Why the clarification, where should we need to change this? I see in the fit method of glm you allow the option of passing niftimasker or multiniftimasker in the documentation but check for niftimasker. In glm.py 187. Then afterwards you check of niftimasker in 296. Shall we change this?

**Comment by bthirion** [comment]
OK, I've been quite inconsistant on this. We should probably rely systematically on MultiNiftiMasker.
I believe that this induces errors in some use cases, but I need to come up with a concrete case.

**Comment by MartinPerez** [comment]
I will take a look around the main code and examples and annotate all parts with inconsistence. I think this go along making the documentation. I guess we still keep niftimasker for beta maps, contrasts and stats?

**Comment by bthirion** [comment]
we still keep niftimasker for beta maps, contrasts and stats? -> not sure what you mean. I don't think that we specifically need dot use a strict NiftiMasker at any place.

**Comment by MartinPerez** [comment]
I might be confused, I assumed beta maps and contrasts are loaded/saved with some masker.

**Comment by bthirion** [comment]
Sure, but this should be the MultiNiftiMasker used to mask the data.

**Comment by bthirion** [comment]
I think I was wrong. Closing.
