### ISSUE TITLE
Nipype interfaces

### ISSUE THREAD

**Issue by TheChymera** [nistats/nistats#49]
Do you plan to provide nipype interfaces for your functions/classes (e.g. `FirstLevelGLM`)?

I am trying to decide whether I should stick to nipype all the way (and force everything - e.g. nistats - into its mold) or move away from it after the preprocessing...

**Comment by MartinPerez** [comment]
I want to write some wrappers for nipype in the future, but its not a priority at the moment.

**Comment by bthirion** [comment]
We should do a  first release of nistats first, but we need more feedback on the API. 
More importanly,  I'm still unsure whether we should handle nistats as a stand-alone project or whether it should be integrated into nilearn.
Any opinion on that ?

**Comment by TheChymera** [comment]
I have used nilearn before due to its (by current python standards) excellent neuroimaging plotting toools. If anything I believe *that* should be split off from nilearn (as niplot perhaps). I think with nistats one would cram even more things into nilearn which in fact have little to do with "learn". Name-wise at least, it would make more sense to integrate nilearn in nistats.

**Comment by TheChymera** [comment]
@MartinPerez I might actually want to help you with that. What I would like to write an interface for first, would be `FirstLevelGLM` . I am familiar with wrapping python functions and command line tools into nipype interfaces, but how would I do that with a *class*?

**Comment by MartinPerez** [comment]
@TheChymera as I understand to wrap a 'class', you can execute the code and link the generated fields of the object to the named outputs in the nipype wrapper.

**Comment by TheChymera** [comment]
@MartinPerez what'S the roadmap on a first release?

**Comment by bthirion** [comment]
We need to stabilize the API to avoid breaking it in the future. 
We're probably going to work on it and get feedback at the next Brainhack in Paris (Feb 24-26 IIRC).

**Comment by TheChymera** [comment]
@bthirion @MartinPerez how is the API coming along? Will you be joining us in Lausanne?

**Comment by bthirion** [comment]
Unfortunately I cannot. I'll be at OHBM though, and we can meet there.
The project is quite active currently, following the steps discussed in  #65. Don't hesistate to jump in if you have suggestions on the PRs.

**Comment by TheChymera** [comment]
I guess the original question - regarding nipype Interfaces is sorted out. We'll just have to look forward to a first stable release. Which is another matter entirely.
