### ISSUE TITLE
[design matrix] error occurs when drift order = 1

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#50]
This happens e.g. when period cut is set longer than the experiment duration.

**Comment by MartinPerez** [comment]
@bthirion how should we go about this? Should I add a value error check or this should be handled gracefully, just throwing a warning and changing the period cut appropriately? I think it makes sense for me to take care of this now, found this error during testing.

**Comment by bthirion** [comment]
Sounds good.

**Comment by bthirion** [comment]
This has been solved as far as I can see. Closing.
