### ISSUE TITLE
Enforce BIDS standard in task description

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#52]
for instance, task identifier is not 'name' but 'trial_type'

**Comment by MartinPerez** [comment]
I think this is related to #23. Maybe its time for me to recontact Poldrack's group? and try to work on the fetcher and object to extract automatically fMRI from a BIDS dataset?

**Comment by bthirion** [comment]
You could first take a look at
http://bids.neuroimaging.io/bids_spec1.0.0-rc2.pdf
if you haven't yet.
Best,

**Comment by MartinPerez** [comment]
I already checked it in detail recently. Three months ago they still did not have the datasets available under the format BIDS and there were still some features available in openFmri not taken into account. I think they are close now to finish their dataset migration.
