### ISSUE TITLE
Getting at residuals after FIR-model-regression

### ISSUE THREAD

**Issue by rschmaelzle** [nistats/nistats#66]
Hi all,
I am not sure this is the right place to post (vs. neurostars?) since my question is in between a help call and an enhancement/documentation request - probably more of the former. I am trying to regress out task-related effects from fMRI data via FIR in order to not have to worry about wrong hemodynamics too much. I managed to set up the design matrix and estimate it:
```
hrf_model = 'FIR' #'Canonical With Derivative'
design_matrix = make_design_matrix(frame_times, paradigm, drift_model='polynomial',
                        drift_order=3, hrf_model = hrf_model, 
                        add_regs= motion, add_reg_names= reg_names, fir_delays=range(1,5)) #
plot_design_matrix(design_matrix)
fmri_glm = FirstLevelGLM().fit(fmri_img, design_matrix)
```
Now I am stuck trying to get at the residuals. Browsing through the examples I can get the contrasts (FIR-results would be interesting per se), but how would I proceed to do sth. along the lines of 
`resid = y_act - y_hat 
#then convert resid into a 4d-nii-image and continue with e.g. nilearn to extract data from nodes?
`
Nistats looks really superpromising! Thanks!
Ralf.

**Comment by bthirion** [comment]
Dear Ralf,
 
We haven't included this feature in the nistats API.
I think that, if you're indeed interested in regressing out the effect related to a FIR model, my suggestion is to get the array of values in the design matrix that you have created, and then give them as `confound` argument to some `masker.transform()` application, where `masker` is a nilearn NiftiMasker. This will output some 'residual' times series. you can map them back to 4D NiftiImage using the masker.inverse_transform() method. 
HTH,

Bertrand

**Comment by rschmaelzle** [comment]
Dear Bertrand,
that's the solution! Thanks so much! Still trying to do things the old-fashioned pre-python way: brain-space, classical modeling ... habits of thinking...
Best Ralf.
