### ISSUE TITLE
beta/contrast maps for constant

### ISSUE THREAD

**Issue by rschmaelzle** [nistats/nistats#67]
Hello,
I am trying to write out a nifti-image for the contrast of the "constant" (i.e. the last regressor in the design matrix consisting of only ones). My code for the contrasts looks like this:

` z_map, t_map, eff_map, var_map  = fmri_glm.transform(contrast_val, contrast_name=contrast_id, output_z=True,  output_stat=True, output_effects=True, output_variance=True)                            

eff_map_image_path = path.join(target_dir, subjs[curr_sub] + '_' + contrast_id + '_eff_map_map.nii')
        nib.save(eff_map, eff_map_image_path)   #and same for t_map, eff_map, var_map etc`

Looping this over my sample, I produce a lot of contrasts and their respective z-,t-, and eff-images that all look pretty reasonable. But the [constant](https://drive.google.com/open?id=0B-sCgoERRQPaUmxtcVlDTENHcms) doesn't. In particular, my assumption was that the eff_map would correspond to the 'beta' images, and that the beta-image for the constant would represent basically the mean across time (although different packages use weird scaling that I don't fully understand). However, instead of finding values around 100, 400, or even 2000 (depending on the raw values from the scanner), the "eff_map" images for the constant have positive and negative values. Seems I doing something very wrong here, but I couldn't find a solution by going through the code. So basically the question is: does the eff_map represent what I think of as beta (or the contrast - which in case of the constant should be identical)? Is there anything else to consider (in setting up the fmri_glm i am setting standardize to False)?

Perhaps I should say that my ultimate goal is to extract data from ROIs (for which I'd want the interesting effect and the constant image), which I'd do via nilearn (and also 2nd level modeling using the mass-univariate example therein). 
Thanks, Ralf.

**Comment by bthirion** [comment]
Have you set `percent_signal_change=False` when instantiating the glm ?
Best,

Bertrand

**Comment by rschmaelzle** [comment]
that was it, sorry! I had missed that it is set true by default. Still not fully understanding all implications and minute differences between SPM and nistats, but results now look reasonable and the overall pattern between nistats and SPM looks very similar. Thanks for getting me back on track ...
Best, 
Ralf
