### ISSUE TITLE
Extreme memory consumption

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#70]
I got the impression in my own datasets that memory consumption was extreme. I was consuming around 22 gb with only 5 runs corresponding to one hour of acquisition with 1.5 mm voxels. and started to get memory errors from other programs like ANTS, that is also memory hungry.

So I started profiling memory consumption of the fmri fit within the examples:

Here is memory consumption for the simple localizer example that loads a 30mb nifti file. the fmri fit explodes to 500mb after having only 100mb in memory. 

![nistats_memprofile_30-05-2016](https://cloud.githubusercontent.com/assets/8766915/15658262/9d4e1e82-26ba-11e6-9036-e5a3312cb9fb.png)

Here is the profile for the fiac analysis example

![nistats_memprofile2_30-05-2016](https://cloud.githubusercontent.com/assets/8766915/15658503/6eab723e-26bd-11e6-897a-75d79e547e87.png)

I think this has to be handled with high priority. Likely in my latest dataset with 16 runs over 2 sessions it will crash. Will test it soon.

**Comment by bthirion** [comment]
I think that this one has been solved
