### ISSUE TITLE
AR model computation is not consistent in python 3

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#77]
commented check in test_first_level_model.py in function test_first_level_model_glm_computation at l. 269 raises the unexpected error.

**Comment by MartinPerez** [comment]
assert_array_almost_equal up to 5 decimals seem to be failing randomly and could be link to this issue

**Comment by bthirion** [comment]
Should we close that one ?

**Comment by MartinPerez** [comment]
Not yet.
