### ISSUE TITLE
Work with FSL-like txt file to handle experimental paradigms

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#8]
To work seamlessly on OpenfMRI datasets.

**Comment by MartinPerez** [comment]
I am on this

**Comment by dohmatob** [comment]
Any progress ? You may consider looking at this boiler-plate-code https://github.com/dohmatob/pypreprocess/blob/master/pypreprocess/fsl_to_nipy.py.

**Comment by MartinPerez** [comment]
this is obsolete now working with bids. Please close.

**Comment by MartinPerez** [comment]
@bthirion please close this too

**Comment by dohmatob** [comment]
On Thu, Jun 16, 2016 at 7:55 PM, Martin Perez-Guevara <
notifications@github.com> wrote:

> @bthirion <https://github.com/bthirion> please close this too
>
IMHO, if you have good reasons to think an issue is obsolete, you just go
ahead and close it yourself, with an appropriate comment like "Ok, this one
seems obsolete; I'm closing it for now". Or use an equivalent method.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/nistats/nistats/issues/8#issuecomment-226562835>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAms1BTWfuyNsvhpmvOeLoG48cjk2rG9ks5qMY4SgaJpZM4FY2BU>
> .
>



-- 
Elvis Dohmatob,
*sent from my  potato...*
http://dohmatob.blogspot.fr/, https://team.inria.fr/parietal/elvis/,
https://github.com/dohmatob

**Comment by MartinPerez** [comment]
@dohmatob I dont have the administrative rights to close issues I did not create, I literally can not see the close issue button. Otherwise of course I would have closed the issue myself.
