### ISSUE TITLE
[BUG] slice_time ref should be optional

### ISSUE THREAD

**Issue by bthirion** [nistats/nistats#84]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/lib/python2.7/dist-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/home/parietal/bthirion/spatial_definition.py in <module>()
     68 # GLM specification and fit
     69 fmri_glm = FirstLevelModel(mask, standardize=False, noise_model='ols')
---> 70 fmri_glm.fit(func_filename, df)
     71 
     72 # contrast

/home/parietal/bthirion/.local/lib/python2.7/site-packages/nistats-0.1.0.dev0-py2.7.egg/nistats/first_level_model.pyc in fit(self, run_imgs, paradigms, confounds, design_matrices)
    333                                  ' to compute design from paradigm')
    334             if self.slice_time_ref is None:
--> 335                 raise ValueError('slice_time_ref not given to FirstLevelModel'
    336                                  ' object to compute design from paradigm')
    337         else:

ValueError: slice_time_ref not given to FirstLevelModel object to compute design from paradigm

The docstring say it defaults  to 0.

**Comment by MartinPerez** [comment]
I initially had 0 as default and then reconsidered (then forgot to update the doc string), I thought that this parameter being part of the preprocessing step should always be specified to make sure the user do not interpret it as a reasonable default argument and becomes aware of its importance. What do you think? Maybe I am exaggerating a bit the importance of the argument? should I fix the doc string or effectively make the default 0?

**Comment by MartinPerez** [comment]
I am giving to slice_time_ref the same importance and message as not providing the t_r.

**Comment by bthirion** [comment]
I think that this is not so important. I prefer to default to zero.

**Comment by MartinPerez** [comment]
@bthirion please close this issue
