### ISSUE TITLE
[BUG] strange estimation artifacts outside of the EPI

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#86]
I think there is an artifact when we try to estimate a model on voxels outside of the EPI. Typically the cerebellum is in the brain mask but not in the EPI. I am not sure how SPM deals with this but we certainly should too.

Our case:
![sub-01_task-languagelocalizer_language-string](https://cloud.githubusercontent.com/assets/8766915/16669527/4a687b28-4496-11e6-9b90-d753f9120674.png)

SPM:
![language_-_string_glass](https://cloud.githubusercontent.com/assets/8766915/16669561/82c21542-4496-11e6-852e-09bc0186399f.png)

**Comment by bthirion** [comment]
I think that there is a numerical issue with null variance in these 
regions ... We should indeed take care of that.

**Comment by MartinPerez** [comment]
Finally this issue was due to wrong inputs given to the masker. by mistake on file names I was giving a mask not in the same space and would have expected a warning to be raised if such mistake happened. I have no idea of what the masker is outputting in that case, but I think is not looking more into it.

Nonetheless should a warning be given when the mask and images are not in the same space? it would have been very useful to me.

**Comment by bthirion** [comment]
By construction, NiftiMaskers can take images that are not in the same space: if your mask is derives from a 2mm-resolution anatomical image, you may want to apply it to 3mm-sampled fMRI data. 
I understand that a warning might be helpful so I'm +1 on the idea.

**Comment by bthirion** [comment]
Looks like a Nilearn issue. Closing.

**Comment by MartinPerez** [comment]
Actually, I have been running second level analysis on already normalized images, if I use the template mask that includes a portion of empty voxels then this comes up again. So it was not the Masker, it was just that the mistake I did before created empty voxels.

I would reopen this since Im sure its a real annoying issue at second level analysis, where people are likely to use the mask of the template in the common space instead of trying to derive a new one. Maybe we should recommend by default to let the Nilearn masker infer the mask instead?

**Comment by MartinPerez** [comment]
I think we should be able to handle the case of empty voxels gracefully...

**Comment by bthirion** [comment]
* What do you call an "empty voxel" ? It is a voxel with NaNs ? or, where the input value is 0 ? Then, in any case, what should we do: spit a warning, impute by zero and do our business ? Or use statistical procedures that can bypass the issue ? 
* In general, first level masking with subject-specific mask is really bad practice: whenever you know that you're going to do a group study, you should enforce a common group mask (see e.g. canica in Nilearn).
* In any case, we should first merge #78.

**Comment by MartinPerez** [comment]
+ By empty I mean they have input value 0. Or very close to 0. I would vote for detecting this artifact and inputting 0.
+ Actually this issue came up first while enforcing a common template mask on all subjects. All data is already in the MNI space before GLM estimation. Already when plotting the glass brain on each of them I get the artifact. This is why I think other people will encounter it, as long as their common mask allow empty spots for some of the subjects this will happen when they plot. Other software manages to avoid this even if the common mask have empty spots.
+ I was avoiding this by computing the EPI mask at first level, then using the intersection of subjects masks for second level. But I agree its a bad practice.
