### ISSUE TITLE
Permutation statistics

### ISSUE THREAD

**Issue by TheChymera** [nistats/nistats#87]
I guess everybody here is familiar with this recent publication: http://www.pnas.org/content/113/28/7900.full

I expect many people in neuroimaging will want to migrate towards permutation tests. Are you planning to include anything of that sort in nistats?

**Comment by bthirion** [comment]
Sure ;-) 
Yes, we have some old code from nipy and Martin has some branches that include this. We wait for second-level analysis API to be stabilized, as this represents the best use case for this approach. 

Best, 

Bertrand

**Comment by TheChymera** [comment]
@bthirion doesn't (e.g.) BROCCOLI also use permutation testing for the first level analysis?

**Comment by bthirion** [comment]
First level permutation tests are hard to implement correctly due to non-iid data. So I'm not particularly enthusiastic about implementing them ;-)
If you think of fMRI, rather than permuting the observations, you may actually want to permute the design (shuffle labels associated with events), which is a bit complicated.

**Comment by TheChymera** [comment]
`non-iid` you mean non-independent - as in temporal autocorrelation?

I've looked at [the broccoli](http://journal.frontiersin.org/article/10.3389/fninf.2014.00024/full) paper again, and indeed they don't seem to do first-level permutation testing. They instead implement “Bayesian first-level fMRI analysis using a Gibbs sampler.”.

**Comment by bthirion** [comment]
Yes: temporal autocorrelation.
Conceptually, Bayesian Analysis is different from classical inference: it does give you no guarantee on the false positive rate. In the context of functional neuroimaging, I don't think that it is very useful.

**Comment by bthirion** [comment]
See issue #100. Closing that one.
