### ISSUE TITLE
masker and glm memcache innefficient for first level models

### ISSUE THREAD

**Issue by MartinPerez** [nistats/nistats#90]
Testing memcache on my datasets I realized that it is taking too much time due to expensive check of the images giving by the masker, since the masker and glm are naively memcached separately. Moreover this is inneficient in terms of disk space and I/O cost for our purposes.

I think we should just cache the final output (results_, labels_) considering only the necessary variables (from first level model object parameters and fit method).

What do you think?

**Comment by bthirion** [comment]
+1

**Comment by bthirion** [comment]
Should we close that one ?

**Comment by MartinPerez** [comment]
not yet

**Comment by bthirion** [comment]
Unlcear what to do exactly. Closing for the moment.
